export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SET_AUTH_ERROR = 'SET_AUTH_ERROR';
export const SET_AUTH_LOGOUT = 'SET_AUTH_LOGOUT';
export const UPDATE_CURRENT_USER = 'UPDATE_CURRENT_USER';
