export default {
  homeScreen: 'Home',
  searchScreen: 'Search',
  cartScreen: 'Cart',
  wishlistScreen: 'Wishlist',
  profileScreen: 'Profile',
  loginScreen: 'Login',
  signUpScreen: 'SignUp',
  productScreen: 'Product',
  changePasswordScreen: 'Change Password',
  editProfileScreen: 'Edit Profile',
  ordersScreen: 'Orders',
  rootScreen: 'rootScreen',
  rootAuthScreen: 'rootAuthScreen',
  profileTab: 'profileTab',
  homeTab: 'homeTab',
  wishlistTab: 'wishlistTab',
  searchTab: 'searchTab',
};
