export default {
  homeScreen: 'Home',
  searchScreen: 'Search',
  cartScreen: 'Cart',
  profileScreen: 'Profile',
  loginScreen: 'Login',
  signUpScreen: 'SignUp',
  changePasswordScreen: 'Change Password',
  editProfileScreen: 'Edit Profile',
  ordersScreen: 'Orders',
  rootScreen: 'rootScreen',
  rootAuthScreen: 'rootAuthScreen',
  productHomeScreenTab: 'productHomeScreenTab',
  productCartScreenTab: 'productCartScreenTab',
  productSearchScreenTab: 'productSearchScreenTab',
  productProfileScreenTab: 'productProfileScreenTab',
  profileTab: 'profileTab',
  homeTab: 'homeTab',
  cartTab: 'cartTab',
  searchTab: 'searchTab',
};
